// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupData():Promise<string>;

export function CheckRequirements():Promise<main.HealthCheckResult>;

export function DeletePreviewScreenshots(arg1:string):Promise<void>;

export function FetchTMDBIDs(arg1:string,arg2:boolean):Promise<main.TMDBResult>;

export function GenerateScreenshots(arg1:string,arg2:number):Promise<Array<main.ScreenshotResult>>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetFileInfo(arg1:string):Promise<Record<string, string>>;

export function GetPythonConfig():Promise<string>;

export function GetRecentUploads(arg1:number):Promise<Array<main.UploadEntry>>;

export function GetSettings():Promise<main.AppSettings>;

export function InitDB():Promise<void>;

export function ManualTerminalInput(arg1:string):Promise<void>;

export function ParseMediaInfo(arg1:string):Promise<Record<string, string>>;

export function PostUploadMove(arg1:string,arg2:string):Promise<void>;

export function PreviewEpisodes(arg1:string,arg2:string):Promise<Array<string>>;

export function RecordUpload(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SavePythonConfig(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function StartUpload(arg1:main.UploadRequest):Promise<void>;

export function StopUpload():Promise<void>;

export function UpdateEngine():Promise<string>;

export function ValidateMedia(arg1:string):Promise<Array<string>>;
