// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupData() {
  return window['go']['main']['App']['BackupData']();
}

export function CheckRequirements() {
  return window['go']['main']['App']['CheckRequirements']();
}

export function DeletePreviewScreenshots(arg1) {
  return window['go']['main']['App']['DeletePreviewScreenshots'](arg1);
}

export function FetchTMDBIDs(arg1, arg2) {
  return window['go']['main']['App']['FetchTMDBIDs'](arg1, arg2);
}

export function GenerateScreenshots(arg1, arg2) {
  return window['go']['main']['App']['GenerateScreenshots'](arg1, arg2);
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetPythonConfig() {
  return window['go']['main']['App']['GetPythonConfig']();
}

export function GetRecentUploads(arg1) {
  return window['go']['main']['App']['GetRecentUploads'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function InitDB() {
  return window['go']['main']['App']['InitDB']();
}

export function ManualTerminalInput(arg1) {
  return window['go']['main']['App']['ManualTerminalInput'](arg1);
}

export function ParseMediaInfo(arg1) {
  return window['go']['main']['App']['ParseMediaInfo'](arg1);
}

export function PostUploadMove(arg1, arg2) {
  return window['go']['main']['App']['PostUploadMove'](arg1, arg2);
}

export function PreviewEpisodes(arg1, arg2) {
  return window['go']['main']['App']['PreviewEpisodes'](arg1, arg2);
}

export function RecordUpload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RecordUpload'](arg1, arg2, arg3, arg4);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SavePythonConfig(arg1) {
  return window['go']['main']['App']['SavePythonConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartUpload(arg1) {
  return window['go']['main']['App']['StartUpload'](arg1);
}

export function StopUpload() {
  return window['go']['main']['App']['StopUpload']();
}

export function UpdateEngine() {
  return window['go']['main']['App']['UpdateEngine']();
}

export function ValidateMedia(arg1) {
  return window['go']['main']['App']['ValidateMedia'](arg1);
}
